# Generated by Django 4.1.4 on 2022-12-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoburger', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='False', default='', upload_to='djangoburger/img'),
        ),
    ]
